### ISSUE TITLE
A draft for the logo

### ISSUE THREAD

**Issue by liwt31** [shuaigroup/Renormalizer#107]
![image](https://user-images.githubusercontent.com/22628546/95717425-84aa0380-0c9f-11eb-84f9-c941d28ed7f4.png)

The image is mostly inspired by:
![image](https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/092-robot-face-1.svg/240px-092-robot-face-1.svg.png)
according to [wikipedia](https://commons.wikimedia.org/wiki/File:092-robot-face-1.svg) it is licensed under the Creative Commons Attribution 4.0 International license.

The font for "renormalizer" is the "transformer font" from this [website](https://www.dafont.com/transformers-movie.font). It is said to be "100% free" and if I understood correctly there is no issue with the license.

If this logo is OK we can put it into our document and readme file.

**Comment by jjren** [comment]
The transformer font is cool.
