### ISSUE TITLE
bug in mp.py add 

### ISSUE THREAD

**Issue by jjren** [shuaigroup/Renormalizer#120]
https://github.com/shuaigroup/Renormalizer/blob/963d52efdaa247320e781a96b64d41c9cadf6f0e/renormalizer/mps/mp.py#L310-L323

In the `add` in mp.py, the `coeff` of mps is not checked. I think it may lead to wrong results sometimes, I will come back to this bug soon.
I plan to carefully re-check the `coeff` stuff and related `normalize` stuff.

**Comment by liwt31** [comment]
Is this issue solved by #124 ?

**Comment by jjren** [comment]
This bug has been resolved. In mps.py, the coeff is compared and is scaled if necessary.
