### ISSUE TITLE
How to define particle number conservation in renormalizer？

### ISSUE THREAD

**Issue by Buantum** [shuaigroup/Renormalizer#126]
for the sake of constructing half-filled fermion-Hubbard model, I need to define Hamiltonian in wanier basis. However, I can't find particle conservation in renormalizer.

**Comment by Buantum** [comment]
what's more, what is the role of “quantum number” in SVD?

**Comment by jjren** [comment]
Currently, renormalizer can only support one conserved quantum number, for example, the total number of electrons.
You can use `Mps.random(model, nelec, M)` to initialize a random MPS with the total number of electrons equal to `nelec`.

Please refer to  `/renormalizer/model/h_qc.py`, in which the ab initio quantum chemistry electronic Hamiltonian is constructed and the antisymmetry of fermion is treated by Jordan-Wigner mapping. 
Additionally, please refer to `/example/h2o_qc.py`, in which the ground state of a water molecule is calculated.

**Comment by Buantum** [comment]
thanks a lot! what i need is electrons number conservation
----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："jjren ***@***.***&gt;;
发送时间：2022年8月11日(星期四) 下午3:59
收件人："shuaigroup/Renormalizer" ***@***.***&gt;;
抄送："钟文彬 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [shuaigroup/Renormalizer] How to define particle number conservation in renormalizer？ (Issue #126)
-----------------------------------

 


Currently, renormalizer can only support one conserved quantum number, for example, the total number of electrons.
 You can use Mps.random(model, nelec, M) to initialize a random MPS with the total number of electrons equal to nelec.

Please refer to  /renormalizer/model/h_qc.py, in which the ab initio quantum chemistry electronic Hamiltonian is constructed and the antisymmetry of fermion is treated by Jordan-Wigner mapping.
 Additionally, please refer to /example/h2o_qc.py, in which the ground state of a water molecule is calculated.

**Comment by jjren** [comment]
> what's more, what is the role of “quantum number” in SVD?

The quantum number in SVD will help to decompose the wavefunction coefficient matrix into several block-diagonal subblock, then SVD is applied to only the subblocks to conserve the total quantum number and save computational cost. (otherwise the conservation of quantum number will be violated because of finite machine accuracy).

For example, the left renormalized states have qn_L= 0, qn_L=1 states,  the right ones have qn_R= 0, qn_R=1 states. If the total qn of the wavefunction is 1, then two subblocks are constructed, one is (qn_L=0, qn_R=1), the other is (qn_L=1, qn_R=0).

**Comment by jjren** [comment]
By the way, if you have any trouble in constructing MPO and MPS for Hubbard model, I can write a small example.

**Comment by Buantum** [comment]
> 
Having glanced over `class Mps(MatrixProduct)` , I find that only `random(cls, model: Model, nexciton, m_max, percent=1.0)` owns 'nexciton' which could be used to initialize MPS with electrons conservation. And I want to know how to initialize custom MPS such as |10101> with electrons conservation as well as being in time evolution.

**Comment by jjren** [comment]
The quantum number is controlled by the `basis` and `MPO`, and the conservation is guaranteed during the time evolution.

**Comment by Buantum** [comment]
I would be appreciate it! thanks a lot!

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："jjren ***@***.***&gt;;
发送时间：2022年8月11日(星期四) 下午4:11
收件人："shuaigroup/Renormalizer" ***@***.***&gt;;
抄送："钟文彬 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [shuaigroup/Renormalizer] How to define particle number conservation in renormalizer？ (Issue #126)
-----------------------------------

 


By the way, if you have any trouble in constructing MPO and MPS for Hubbard model, I can write a small example.
