### ISSUE TITLE
The 3rd-party libraries used in Renormalizer 

### ISSUE THREAD

**Issue by jjren** [shuaigroup/Renormalizer#30]
There are several 3rd-party libraries used in Renormalizer.
I would like to list them all and figure out their roles in the whole package. 
Please help to check and finish it. @liwt31 

1. /lib/davidson.py       
https://github.com/pyscf/pyscf/blob/master/pyscf/lib/linalg_helper.py
davidson diagonalization 

2. lib/_ivp
scipy.integrate
solve initial value problem 
(I guess this file is modified for Cupy, right? If the scipy.integrate is upgraded, what should we do?)

3. lib/krylov.py
https://github.com/cmendl/pytenet/blob/master/pytenet/krylov.py
Krylov space method to calculate e^{iH\tau} \Psi

4. utils/qutip_utils.py
It seems that qutip_utils.py calculates the matrix element of some basic operators.

**Comment by liwt31** [comment]
As for 2: it's heavily modified to be compatible with CuPy. In the near future when [NEP18](https://numpy.org/neps/nep-0018-array-function-protocol.html) is enabled, we might be able to use NumPy array and CuPy array interchangeably and the modified lib in `lib/_ivp` will become unnecessary.
As for 4: it's not a third party lib. I wrote them actually.

**Comment by jjren** [comment]
I mean some qutip function like qutip.destroy, qutip.identity.

**Comment by liwt31** [comment]
> I mean some qutip function like qutip.destroy, qutip.identity.

This is okay, otherwise, we need to include NumPy and lots of other packages either.
