### ISSUE TITLE
Refactor how physical observables are calculated in TdMpsJob

### ISSUE THREAD

**Issue by liwt31** [shuaigroup/Renormalizer#32]
In the early days of the project, I decided to store all previously evolved mps in memory, and obtain physical observable from the mps, which is proved to be a design failure, leading to ugly things like `clear_memory`.

A more natural way is to allow users to choose which physical observables to calculate in the time evolution job and discard previously evolved mps after the observables are obtained.

**Comment by jjren** [comment]
The strategy that storing all previously MPSs in memory is not a good idea. I think we can provide different strategies: 
1. save user-defined properties only and dump MPS(t) into disk every several steps for restart purpose. 
1. save MPSs(t_0, t_1, t_2...) in the memory, dump them into disk every several steps and at the same time clear them in the memory.
The first strategy should be the default.

**Comment by liwt31** [comment]
Does the second strategy mean eventually all MPSs are dumped? I don't think it'll be practical and it seems to be a special case of the first strategy.

**Comment by jjren** [comment]
> Does the second strategy mean eventually all MPSs are dumped? I don't think it'll be practical and it seems to be a special case of the first strategy.

No. Only the last step t_n in each dump cycle will be stored into disk and overwritten the former t_n.  It is only for restart purpose.

**Comment by liwt31** [comment]
OK. So the difference is that the first strategy will eventually produce a series of dumped MPS and the second strategy will only save one MPS to disk because previous ones are overwritten?

**Comment by jjren** [comment]
不好意思，我理解错你上一个问题了。
1. 第一个策略是每几步存一个MPS在硬盘里，然后覆盖之前存的，所以只留了一个MPS在硬盘里，做重算的时候用。
2. 第二个策略是每一个时刻的mps都存在硬盘里。这个策略只适用于短时的，m不太大的计算，以及硬盘足够大。估算一下，假如一个100个site的计算，m=50，physicalbond=10，那么一个零温的mps大小为80M，有限温的mps为800M，如果硬盘足够的话存个几百步还是可以的。这个主要是用来做一些debug或者benchmark吧。

**Comment by liwt31** [comment]
After this is done I think we can get rid of `cached_property` which is firstly designed to work with storing all MPSs in memory.

**Comment by liwt31** [comment]
Solved by #124 and previous works
