### ISSUE TITLE
Decide which content should be in wiki

### ISSUE THREAD

**Issue by liwt31** [shuaigroup/Renormalizer#36]
The doc in #29 seems to work quite well, and it contains some contents from the [project wiki](https://github.com/shuaigroup/Renormalizer/wiki). From my point of view, certain contents such as the installation guide should be in the wiki because I wish other people can modify these contents with ease. The doc instead can provide a link to these contents.

IMO, the contents that should be staying in the wiki are:
- Installation guide
- How to read the code

And those that should be moved to the doc:
- How to develop
- How to use

**Comment by jiangtong1000** [comment]
Agree with you, I just copied the wiki directly as currently it just provides a demo version, later we will see how to customize it into detail.
