### ISSUE TITLE
`approx_propagator` in `MpDm` seems obsolete

### ISSUE THREAD

**Issue by liwt31** [shuaigroup/Renormalizer#50]
In `MpDm`  there is a class method `approx_propagator` which tries to construct e^-{iHt} explicitly.

https://github.com/shuaigroup/Renormalizer/blob/50056c674955ff77ac03493b74bce5e171dcce81/renormalizer/mps/mpdm.py#L118-L139

Currently, the code is barely used, only in `ThermalProp`. But sadly the optional argument is not used either and there seems to be a bug that makes the argument take no effect.

https://github.com/shuaigroup/Renormalizer/blob/50056c674955ff77ac03493b74bce5e171dcce81/renormalizer/mps/thermalprop.py#L16-L29

IMO the approach of constructing the propagator is inefficient. The argument is the same as multiplying matrices one by one rather than constructing large tensor $H$.

So, I'm thinking of removing the code, which I think will also lead to simplifications of the `evolve` method of `Mps`:

https://github.com/shuaigroup/Renormalizer/blob/50056c674955ff77ac03493b74bce5e171dcce81/renormalizer/mps/mps.py#L509

**Comment by jjren** [comment]
Yes, this is just an experimental evolution method I tested long time ago.  It did not work well.
I agree to remove this method now.
