### ISSUE TITLE
The explicit TD-DMRG/TDH hybrid method will be removed in the future.

### ISSUE THREAD

**Issue by jjren** [shuaigroup/Renormalizer#61]
As tdvp-based evolution schemes are very robust now and TD-DMRG/TDH could be embedded in tdvp-based schemes implicitly with some virtual bonds M=1,  there is no reason to keep the explicit TD-DMRG/TDH algorithm anymore.  I plan to remove it in the near future.
Some coding is needed:
1. A new MPO scheme which puts the Hartree DoFs at the end of the chain.

**Comment by liwt31** [comment]
I think it'll be nice if we can carry out careful benchmarks between the two schemes, in terms of accuracy and efficiency, for MPO scheme 2, 3, 4.

**Comment by jjren** [comment]
Sure. I will keep the old one and do some comparisons, and then decide if we should remove it or not.
