### ISSUE TITLE
What kind of operators does this efficient hash algorithm support?

### ISSUE THREAD

**Issue by jjren** [shuaigroup/Renormalizer#74]
https://github.com/shuaigroup/Renormalizer/blob/10a3403abfeaf48e7ece994bbdab3c7042168b39/renormalizer/mps/mps.py#L389-L397
@liwt31

**Comment by liwt31** [comment]
It works with an array of MPOs that can be represented as follows assuming there are 5 sites in total:
```
{AXXXX, XAXXX, XXAXX, XXXAX, XXXXA}
```
where the order does not matter.
In the current code, usually `X` is identity and `A` is some local operator such as `a^\dagger a`

**Comment by jjren** [comment]
Comments have been added to the new code.
