### ISSUE TITLE
Removing support for JSON dump format. 

### ISSUE THREAD

**Issue by liwt31** [shuaigroup/Renormalizer#86]
In TdMpsJob `JSON` and `npz` dump format are supported. In my experience `JSON` format is rarely useful, because:
- It costs lots of disk space
- It does not support complex number

The only good point about `JSON` format is that the dumped file is directly readable by text editors such as `vim`, however, the feature is rarely used.

On the other hand, trying to support `JSON` leads the inconviences such as the over usage of the `cast_float` function.

If there is no special need for the `JSON` format, I'm going to remove support for JSON dump format.

**Comment by jjren** [comment]
Agree.

**Comment by jjren** [comment]
Solved.
