### ISSUE TITLE
Another basis for multi electron on one site

### ISSUE THREAD

**Issue by liwt31** [shuaigroup/Renormalizer#89]
The basis `BasisMultiElectron` features flexibility, and a down side is that lots of default behavior are not well-defined. For example, the `gs` method for `Mps` have to be careful with the specific parameter of the basis:
https://github.com/shuaigroup/Renormalizer/blob/ede2b6964fde1ede2eede62880d9938aae4be602/renormalizer/mps/mps.py#L337-L341
This continues the discussions in #82 .

I propose to add another basis for the case where multi electron is on the same site. The quantum number of the basis is constantly `[0] + [1] * (n-1)` and thus creation/annihilation operators and the ground state are well defined. 
The basis should be very useful at least in charge transport problems, which justifies the necessity to add a specific class.
The new basis could be named as `BasisMultiElectronVac` to indicate that the basis includes the vacuum state. 
The transform from scheme 4 to `MolList2` should use this basis by default for maximum backward compatibility. A flag to determine which basis to use might be added if proved necessary.

**Comment by jiangtong1000** [comment]
I thought the zero exciton state can be naturally added to the current MultiElectronBasis, if needed,  by just letting the corresponding sigmaqn = 0, and this is a flexible class.  I am not so sure about what you plan to do.

**Comment by liwt31** [comment]
> I thought the zero exciton state can be naturally added to the current MultiElectronBasis, if needed, by just letting the corresponding sigmaqn = 0, and this is a flexible class. I am not so sure about what you plan to do.

The problem is that the class is **too flexible** at least for charge transport problems. As you can see from the sample code:
https://github.com/shuaigroup/Renormalizer/blob/ede2b6964fde1ede2eede62880d9938aae4be602/renormalizer/mps/mps.py#L337-L341
the ground state of the basis is not well defined because of the flexibility, and a warning should be issued when trying to occupy the ground state. Note that the warning is in a loop so N warnings will popup where N is the total number of e dof. The warning is not the desired behavior in a large number of cases including charge transport problems.

Another example when calculating reduced density matrix:
https://github.com/shuaigroup/Renormalizer/blob/ede2b6964fde1ede2eede62880d9938aae4be602/renormalizer/mps/mps.py#L1538-L1541
Under the flexible basis the reduced density matrix includes the zero exciton state, because the code is not certain whether this information is useful. However in charge transport problems the information is definitely not useful and the default behavior should exclude the zero exciton state.

The worst problem happens when it comes to the onsite operators for `Mpo`:
https://github.com/shuaigroup/Renormalizer/blob/ede2b6964fde1ede2eede62880d9938aae4be602/renormalizer/mps/mpo.py#L1093-L1098
as explained in the comment. Again for charge transport problems this should not be an issue.

In summary, it seems the current implementation for `BasisMultiElectron` is **too flexible** that a number of essential operations over the basis become ambiguous. 
A straightforward solution is to add some kind of flag to the basis class to indicate that this is not the kind of flexible basis. The drawback of the method is that
- it usually means we have to do more levels of `if` tests in other parts of the code
- more flags are expected for the `BasisMultiElectron` class when it is indeed required to be flexible, such as a flag to determine the intended ground state in the presence of multiple zero exciton state.

So my proposal is to write a new class as a special but very common case of `BasisMultiElectron`. In other parts of the code the class should be very simple to handle and the resulting code should be eazy to write and understand, whereas infinite flexibility can be added to the original `BasisMultiElectron` to meet any corner cases.

**Comment by jjren** [comment]
I agree with Weitang. The new BasisMultiElectronVac could be added to make the current implementation more compatible with the old schemes (scheme4).

**Comment by jjren** [comment]
I think this issue is solved, so I close it.
