### ISSUE TITLE
Remove the chain representation?

### ISSUE THREAD

**Issue by liwt31** [shuaigroup/Renormalizer#90]
When constructing MPO based on `MolList` it is possible to choose star representation or chain representation. As far as I know, the chain representation is seldomly used and not well tested. Besides, the task of choosing representation would be advanced to writing the model if `MolList2` is used and the inconsistency constitutes a barrier to combine `MolList` and `MolList2`.
It'll probably be a good idea to remove the chain representation, which IMO is a legacy of the old `ephMPS`.

**Comment by jjren** [comment]
I agree. Chain representation could be easily used with MolList2 now. So, it could be removed.

**Comment by liwt31** [comment]
I'll see if I can get this done when merging MolList and MolList2.
