### ISSUE TITLE
mpi4py vs. multiprocessing of DDMRG

### ISSUE THREAD

**Issue by jiangtong1000** [shuaigroup/Renormalizer#95]
- currently DDMRG is parallelized  using the `multiprocessing` module for its clean API and easy usage
- `mpi4py` is more sophisticated and is considered to replace `multiprocessing` to gain more speed and also allows parallelization across clusters.

**Comment by jjren** [comment]
i think it is not a urgent task. we could do it when we have time.发自我的华为手机-------- 原始邮件 --------发件人： Tong Jiang <notifications@github.com>日期： 2020年6月15日周一 20:42收件人： shuaigroup/Renormalizer <Renormalizer@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [shuaigroup/Renormalizer] mpi4py vs. multiprocessing of DDMRG (#95)
currently DDMRG is parallelized  using the multiprocessing module for its clean API and easy usagempi4py is more sophisticated and is considered to replace multiprocessing to gain more speed and also allows parallelization across clusters.

**Comment by liwt31** [comment]
Closing the issue since it has been inactive for several years. @jiangtong1000 feel free to reopen if you had your time

**Comment by jiangtong1000** [comment]
> Closing the issue since it has been inactive for several years. @jiangtong1000 feel free to reopen if you had your time

of course, thanks. I will wait until I can find useful cases that TD version can't do. Actually we do have a case that TD can't do very well, we will see.
